# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1dbd4ebaa164a27dd3e652656018b99fa01931120ff0573bccae528e2e1a65eed3aedcb6844ed3abd1dad0c4baeef075affff180aa22ae8d3fb2607af89f870d

test:
  secret_key_base: 55a8628b7d784075fac3a7b8ca9cb98f2e19c35c525e0ba5be65fdc3f933286b1662f5c2e1c0074f591c30b76e5535b556f52a337acf49e5229664bdf07dce4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
